#include <id.h>

namespace dymp{;

const char* VarNames[] = {
	"any"               ,
	"centroid_pos_t"    ,
	"centroid_pos_r"    ,
	"centroid_vel_t"    ,
	"centroid_vel_r"    ,
	"centroid_momentum" ,
	"centroid_time"     ,
	"centroid_duration" ,
	"centroid_end_pos"  ,
	"centroid_end_vel"  ,
	"centroid_end_acc"  ,
	"centroid_end_stiff",
	"centroid_end_cmp",
	"centroid_end_force",
	"centroid_end_moment",
	"wholebody_pos_t",
	"wholebody_pos_r",
	"wholebody_vel_t",
	"wholebody_vel_r",
	"wholebody_acc_t",
	"wholebody_acc_r",
	"wholebody_joint_pos",
	"wholebody_joint_vel",
	"wholebody_joint_acc",
	"wholebody_joint_jerk",
	"wholebody_force_t",
	"wholebody_force_r"
};

const char* ConNames[] = {
	"any"                 ,
	"centroid_pos_t"           ,
	"centroid_pos_r"           ,
	"centroid_vel_t"           ,
	"centroid_vel_r"           ,
	"centroid_momentum"        ,
	"centroid_time"            ,
	"centroid_end_pos_t"       ,
	"centroid_end_pos_r"       ,
	"centroid_des_pos_t"       ,
	"centroid_des_pos_r"       ,
	"centroid_des_vel_t"       ,
	"centroid_des_vel_r"       ,
	"centroid_des_momentum"    ,
	"centroid_des_time"        ,
	"centroid_des_duration"    ,
	"centroid_des_end_pos_t"   ,
	"centroid_des_end_vel_t"   ,
	"centroid_des_end_pos_r"   ,
	"centroid_des_end_vel_r"   ,
	"centroid_des_end_stiff"   ,
	"centroid_des_end_cmp"     ,
	"centroid_des_end_force"   ,
	"centroid_des_end_moment"  ,
	"centroid_duration_range"  ,
	"centroid_end_pos_range"   ,
	"centroid_end_stiff_range" ,
	"centroid_end_contact"     ,
	"centroid_end_friction"    ,
	"centroid_end_moment_range",
	"wholebody_pos_t",
	"wholebody_pos_r",
	"wholebody_vel_t",
	"wholebody_vel_r",
	"wholebody_acc_t",
	"wholebody_acc_r",
	"wholebody_joint_pos",
	"wholebody_joint_vel",
	"wholebody_joint_acc",
	"wholebody_joint_jerk",
	"wholebody_force_t",
	"wholebody_force_r",
	"wholebody_limit",
	"wholebody_contact_pos_t",
	"wholebody_contact_pos_r",
	"wholebody_contact_vel_t",
	"wholebody_contact_vel_r",
	"wholebody_normal_force",
	"wholebody_friction_force",
	"wholebody_moment",
	"wholebody_momentum"
};

}
